# Generated by Django 2.2.1 on 2019-05-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190526_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('user_name', 'college')},
        ),
    ]
