# Generated by Django 2.2.1 on 2019-05-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190527_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('user_name', 'college')},
        ),
    ]
